src/Gospel/Bundle/CoreBundle/Entity/Partner.php
<?php

/*
 * 文章的模型
 */
namespace Gospel\Bundle\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Partner
 * 
 * @Annotation
 * @ORM\Table(name="gospel_partner")
 * @ORM\Entity(repositoryClass="Gospel\Bundle\CoreBundle\Entity\PartnerRepository")
 * @ORM\HasLifecycleCallbacks
 * @partner Zhili He <zhili850702@gmail.com, http://zhilihe.com/>
 */
class Partner
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

	private $tempCover;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="phone", type="string", length=255, nullable=true)
     */
    private $phone;


    /**
     * @var string
     *
     * @ORM\Column(name="address", type="string", length=255, nullable=true)
     */
    private $address;


	/**
     * @ORM\Column(name="cover_path", type="string", length=255, nullable=true)
     */
    public $coverPath;

	/**
     * @ORM\Column(name="partner_path", type="string", length=255, nullable=true)
     */
    public $partnerPath;

	/**
     * @Assert\File(maxSize="6000000")
     */
    private $cover;


    /**
     * @var string
     *
	 * @ORM\ManyToOne(targetEntity="Gospel\Bundle\CoreBundle\Entity\Category")
	 * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text", nullable=true)
     */
    private $content;

    /**
     * @var integer
     *
     * @ORM\Column(name="sortOrder", type="integer", nullable=true)
     */
    private $sortOrder;

    /**
     * @var integer
     *
     * @ORM\Column(name="promotionStatus", type="boolean", nullable=true)
     */
    private $promotionStatus;

    /**
     * @var integer
     *
     * @ORM\Column(name="status", type="boolean", nullable=true)
     */
    private $status;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createAt", type="datetime", nullable=true)
     */
    private $createAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="publishedAt", type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @var integer
     *
     * @ORM\Column(name="stopPublish", type="boolean", nullable=true)
     */
    private $stopPublish;


    /**
     * @var \DateTime
     *
     * @ORM\Column(name="stopPublishedAt", type="datetime", nullable=true)
     */
    private $stopPublishedAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updatedAt", type="datetime", nullable=true)
     */
    private $updatedAt;


    public function setId($id)
    {
        $this->id = $id;
		return $this;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Partner
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Partner
     */
    public function setUrl($url)
    {
        $this->url = $url;
    
        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Partner
     */
    public function setContent($content)
    {
        $this->content = $content;
    
        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set promotionStatus
     *
     * @param integer $promotionStatus
     * @return Partner
     */
    public function setPromotionStatus($promotionStatus)
    {
        $this->promotionStatus = $promotionStatus;
    
        return $this;
    }

    /**
     * Get promotionStatus
     *
     * @return integer 
     */
    public function getPromotionStatus()
    {
        return $this->promotionStatus;
    }

    /**
     * Set status
     *
     * @param integer $status
     * @return Partner
     */
    public function setStatus($status)
    {
        $this->status = $status;
    
        return $this;
    }

    /**
     * Get status
     *
     * @return integer 
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set createAt
     *
     * @param \DateTime $createAt
     * @return Partner
     */
    public function setCreateAt($createAt)
    {
        $this->createAt = $createAt;
    
        return $this;
    }

    /**
     * Get createAt
     *
     * @return \DateTime 
     */
    public function getCreateAt()
    {
        return $this->createAt;
    }

    /**
     * Set createAt
     *
     * @param \DateTime $createAt
     * @return Partner
     */
    public function setPublishedAt($publishedAt)
    {
        $this->publishedAt = $publishedAt;
    
        return $this;
    }

    /**
     * Get publishedAt
     *
     * @return \DateTime 
     */
    public function getPublishedAt()
    {
        return $this->publishedAt;
    }

    /**
     * Set createAt
     *
     * @param \DateTime $createAt
     * @return Partner
     */
    public function setStopPublishedAt($stopPublishedAt)
    {
        $this->stopPublishedAt = $stopPublishedAt;
    
        return $this;
    }

    /**
     * Get stopPublishedAt
     *
     * @return \DateTime 
     */
    public function getStopPublishedAt()
    {
        return $this->stopPublishedAt;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
    }
    
	public function __toString()
	{
		return $this->title;
	}

    /**
     * Set category
     *
     * @param \Gospel\Bundle\CoreBundle\Entity\Category $category
     * @return Partner
     */
    public function setCategory(\Gospel\Bundle\CoreBundle\Entity\Category $category = null)
    {
        $this->category = $category;
    
        return $this;
    }

    /**
     * Get category
     *
     * @return \Gospel\Bundle\CoreBundle\Entity\Category 
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Partner
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    
        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set stopPublish
     *
     * @param boolean $stopPublish
     * @return Partner
     */
    public function setStopPublish($stopPublish)
    {
        $this->stopPublish = $stopPublish;
    
        return $this;
    }

    /**
     * Get stopPublish
     *
     * @return boolean 
     */
    public function getStopPublish()
    {
        return $this->stopPublish;
    }

    /**
     * Set type
     *
     * @param boolean $type
     * @return Partner
     */
    public function setType($type)
    {
        $this->type = $type;
    
        return $this;
    }

	/**
     * Sets cover.
     *
     * @param UploadedCover $cover
     */
    public function setCover(UploadedFile $cover = null)
    {
        $this->cover = $cover;
		// 检查是否有旧的文件，如果有保存到临时变量里面，当更新的时候进行删除
		if (isset($this->coverPath)) {
			$this->tempCover = $this->coverPath;
			$this->coverPath = null;
		} else {
			$this->coverPath = null;
		}
    }

    /**
     * Get cover.
     *
     * @return UploadedCover
     */
    public function getCover()
    {
        return $this->cover;
    }

	/**
	 * @ORM\PrePersist()
	 * @ORM\PreUpdate()
	 */
	public function preUpload()
	{
		if (null !== $this->getCover()) {
			// 生成一个独一无二的名字
			$coverName = sha1(uniqid(mt_rand(), true));
			$this->coverPath = $coverName . '.' . $this->getCover()->guessExtension();
		}
	}

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null !== $this->getCover()) {
            // 如果是在移动文件的时候出现错误，
            // move()函数会扔出异常，从而阻止内容被保存到数据库
            $this->getCover()->move($this->getAbsoluteCoverPath(), $this->coverPath);

            // 查看是否有旧的文件
            if (isset($this->tempCover)) {
                //删除旧的文件
                unpartner($this->getAbsoluteCoverPath().DIRECTORY_SEPARATOR.$this->tempCover);
            }
        }
        return;
    }

    /**
     * @ORM\PostRemove()
     */
    public function remove()
    {
        if ($coverPath = $this->getCoverPath()) {
            unpartner($this->getAbsoluteCoverPath().DIRECTORY_SEPARATOR.$coverPath);
        }
    }

    public function getCoverPath()
    {
        return $this->coverPath;
    }

    /**
     * 封面图片的相对路径
     */
	public function getCoverWebPath()
	{
		return 'assets/media/partner/cover';
	}
    
    /**
     * 封面图片的路径
     */
	public function getCoverWebUrl()
	{
		return $this->getCoverWebPath() . DIRECTORY_SEPARATOR . $this->getCoverPath();
	}

    /**
     * 服务器的根路径
     */
	public function getWebRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return $_SERVER['DOCUMENT_ROOT'];
    }

    public function getAbsoluteCoverPath()
    {
        return $this->getWebRootDir() . DIRECTORY_SEPARATOR . $this->getCoverWebPath();
    }

src/Gospel/Bundle/CoreBundle/Controller/PartnerController.php
<?php

namespace Gospel\Bundle\CoreBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sylius\Bundle\ResourceBundle\Controller\ResourceController;
use Gospel\Bundle\CoreBundle\Form\PartnerType;
use Gospel\Bundle\CoreBundle\Form\PartnerSearchType;
use Gospel\Bundle\CoreBundle\Entity\Partner;
use Symfony\Component\Filesystem\Filesystem;

/**
 *
 * @link Zhili He <zhili850702@gmail.com, http://zhilihe.com/>
 */
class PartnerController extends ResourceController
{
    /**
     * Get collection (paginated by default) of resources.
     */
    public function indexAction(Request $request)
    {
        $config = $this->getConfiguration();

        $resource = $this->createNew();
		$form = $this->createForm(new PartnerSearchType(), $resource, array(
    		'em' => $this->getDoctrine()->getManager(),
		));

		$metadata = $this
                 ->getManager()
                 ->getMetadataFactory()
                 ->getMetadataFor("Gospel\Bundle\CoreBundle\Entity\Partner");
        $criteria = $config->getCriteria();
		$gospel = $request->get('gospel_partner_search', array());
		$likes = array('title', 'email', 'phone');
		foreach($gospel as $field => $val) {
			if($val) {
				if (in_array($field, $likes)) {
					$val = array(
						'type' => 'like',
						'data' => $val,
					);
				}
				if($field == 'category') {
					$val = $this->getDoctrine()->getManager()->getRepository('GospelCoreBundle:CategoryPartner')->find($val);
				}
				if (!$metadata->hasField($field) && $field != 'category') {
					// Make sure we only use existing fields (avoid any injection)
					continue;
				}
				$criteria[$field] = $val;
			}
		}
        $sorting = $config->getSorting();

        $pluralName = $config->getPluralResourceName();
        $repository = $this->getRepository();

        if ($config->isPaginated()) {
            $resources = $this
                ->getResourceResolver()
                ->getResource($repository, $config, 'createPaginator', array($criteria, $sorting))
            ;

            $resources
                ->setCurrentPage($request->get('page', 1), true, true)
                ->setMaxPerPage($config->getPaginationMaxPerPage())
            ;
        } else {
            $resources = $this
                ->getResourceResolver()
                ->getResource($repository, $config, 'findBy', array($criteria, $sorting, $config->getLimit()))
            ;
        }

        $view = $this
            ->view()
            ->setTemplate($config->getTemplate('index.html'))
            ->setTemplateVar($pluralName)
            ->setData(array(
				$pluralName => $resources,
				'form' => $form,
				)
			)
        ;

        return $this->handleView($view);
    }
    public function createAction(Request $request)
    {
        $config = $this->getConfiguration();

        $resource = $this->createNew();
		$form = $this->createForm(new PartnerType(), $resource, array(
    		'em' => $this->getDoctrine()->getManager(),
			'createAt' => new \DateTime(),
			'entity' => $resource,
		));

        if (($request->isMethod('POST') || $request->isMethod('PUT') ) && $form->bind($request)->isValid()) {
			// 创建
            $this->create($resource);
            $this->setFlash('success', 'create');

            return $this->redirectTo($resource);
        }

        if ($config->isApiRequest()) {
            return $this->handleView($this->view($form));
        }

        $view = $this
            ->view()
            ->setTemplate($config->getTemplate('create.html'))
            ->setData(array(
                $config->getResourceName() => $resource,
                'form'                     => $form->createView(),
				// 传递到另外一个地方的表单
                'form2'                     => $form->createView(),
            ))
        ;

        return $this->handleView($view);
    }

    public function updateAction(Request $request)
    {
        $config = $this->getConfiguration();

        $resource = $this->findOr404();
		$form = $this->createForm(new PartnerType(), $resource, array(
    		'em' => $this->getDoctrine()->getManager(),
			'createAt' => $resource->getCreateAt(),
			'entity' => $resource,
		));

        if (($request->isMethod('PUT') || $request->isMethod('POST')) && $form->bind($request)->isValid()) {
            $this->update($resource);
            $this->setFlash('success', 'update');

            return $this->redirectTo($resource);
        }

        if ($config->isApiRequest()) {
            return $this->handleView($this->view($form));
        }

        $view = $this
            ->view()
            ->setTemplate($config->getTemplate('update.html'))
            ->setData(array(
                $config->getResourceName() => $resource,
                'form'                     => $form->createView(),
                'form2'                     => $form->createView(),
                'temp_id'                     => $resource->getId(),
            ))
        ;

        return $this->handleView($view);
    }

	public function makeTree($data, $arr) 
	{
		foreach($data as $row) {
			$arr[$row['id']] = str_repeat("——", $row['lvl']).$row['title'];
			if(is_array($row['__children']) && count($row['__children']) > 0) {
				$arr = $this->makeTree($row['__children'], $arr);
			}
		}
		return $arr;
	}

	private function getCategoryTree()
	{
		$repository = $this->getDoctrine()->getManager()->getRepository('GospelCoreBundle:CategoryPartner');
		$arrayTree = $repository->childrenHierarchy();
		return $arrayTree;
	}

	/**
	 * 导入旧的数据库的数据
	 */
	public function loadAction()
	{
		$repositoryPartner = $this->getDoctrine()->getManager()->getRepository('GospelCoreBundle:Partner');
		$customerEm =  $this->get('doctrine')->getManager('customer');
		$em =  $this->get('doctrine')->getManager('default');
		$result = $repositoryPartner->findAllOld($customerEm);

		// 循环现在的所有的数据然后导入到数据
		foreach ($result as $row) {
			$partner = new Partner();
			$partner->setId($row['id']);
			$partner->setTitle($row['name']);
			$partner->setAddress($row['address']);
			$partner->setPhone($row['telephone']);
			$partner->setCoverPath(basename($row['pic']));
			$partner->setStatus(1);
			$partner->setSortOrder($row['sequence']);
			$partner->setCreateAt(new \DateTime());
			$partner->setUpdatedAt(new \DateTime());
			$em->persist($partner);
			$em->flush();

			// 移动图片
			$fs = new Filesystem();
			$oldImageFile = '/var/www/www.christiantimes.cn/upload/parter/' . basename($row['pic']);
			$newImageFoler = '/var/www/christiantimes.dev/web/assets/media/partner/cover/' 
			;
			$newImageFile = $newImageFoler . basename($row['pic']);
			$fs->mkdir($newImageFoler);
			if (file_exists($oldImageFile) && is_file($oldImageFile)) {
				$fs->copy($oldImageFile, $newImageFile);
			}
		}
	}
}

src/Gospel/Bundle/CoreBundle/Resources/views/Partner/create.html.twig
{% extends 'GospelCoreBundle:Partner:form.layout.html.twig' %}

src/Gospel/Bundle/CoreBundle/Resources/views/Partner/form.layout.html.twig
{% extends '::backend.html.twig' %}
{% form_theme form 'GospelCoreBundle:Macros:misc.html.twig' %}

{% block header %}
<h1 class="page-title">添加合作伙伴</h1>
{% endblock %}
{% block breadcrumb %}
<li><a href="{{ path('gospel_partner_index') }}">合作伙伴列表</a></li>
{% endblock %}

{% block body -%}

	<div class="region region-content">
		<div class="block block-system" id="block-content">
			<div class="content">
            {{ form_errors(form) }}
	  {{ form_start(form) }}
					<div class="btn-toolbar subhead" id="toolbar">
						<div class="form-actions form-wrapper" id="edit-actions"><input type="submit" id="edit-submit" name="op" value="保存" class="btn btn-success"><a  id="" name="op" href="{{ path('gospel_partner_index') }}" class="button form-submit">返回</a>
						</div>
					</div>
					<ul id="myTabs" class="nav nav-tabs">
						<li><a href="#post-details" data-toggle="tab">合作伙伴内容</a></li>
						<li><a href="#post-options" data-toggle="tab">发布选项</a></li>
					</ul>

					<div id="myTabsContent" class="form-horizontal">
						<div id="post-details" class="tab-content active">
							<br/>
							{% from 'GospelCoreBundle:Macros:misc.html.twig' import styleFormRow %}
							{{ styleFormRow(form.title) }}
                            <div class="control-group">
								<div class="controls">
                                  {% if form.vars.value.coverPath %}
                                  <img src="{{ asset(form.vars.value.coverWebPath~'/'~form.vars.value.coverPath) | imagine_filter('88x31') }}" />
                                  {% endif %}
								</div>
                            </div>
							{{ styleFormRow(form.cover) }}
                                  
							{{ styleFormRow(form.url) }}
							{{ styleFormRow(form.content) }}
							{{ styleFormRow(form.address) }}
							{{ styleFormRow(form.phone) }}
							{{ styleFormRow(form.sortOrder) }}
						</div>
								<div id="post-options" class="tab-content">
									<br />
									{{ styleFormRow(form.status) }}
									{{ styleFormRow(form.publishedAt) }}
									{{ styleFormRow(form.stopPublish) }}
									{{ styleFormRow(form.stopPublishedAt) }}
								</div>
								<div id="post-seo" class="tab-content">
									<br />
		{{ form_rest(form) }}
								</div>
							</div>
		{{ form_end(form) }}
						</div>
					</div>
				</div>




{% endblock %}

{% from 'GospelCoreBundle:Macros:misc.html.twig' import rteCss, rteJs %}
{% block stylesheets %}
	{{ parent() }}
	{{ rteCss() }}
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	{{ rteJs("gospel_partner_content") }}
{% endblock %}

src/Gospel/Bundle/CoreBundle/Resources/views/Partner/index.html.twig
{% extends '::backend.html.twig' %}
{%block header %}<h1 class="page-title">合作伙伴管理</h1>{% endblock %}

{% block breadcrumb %}
{% endblock %}

{% block body -%}
<ul class="action-links">
          <li><a class="button button-action" href="{{ path('gospel_partner_new') }}">添加合作伙伴</a></li>
        </ul>
		<form name="" action="" method="get">
			{{ form_widget(form) }}
							<div>
								<input type="submit" name="search" value="筛选" class="btn btn-info"></div>
							<br/>
		</form>
<table id="edit-entities" class="sticky-enabled responsive-enabled tabledrag-processed tableresponsive-processed tableheader-processed sticky-table">
	<thead>
		<tr>
			<th>ID</th>
			<th>封面</th>
			<th>标题</th>
			<th>分类</th>
			<th>审核</th>
			<th>发布日期</th>
			<th>操作</th>
		</tr></thead>
	<tbody>
	{% if partners %}
	{% for entity in partners %}
			<tr class="{{ cycle(['odd', 'even'], loop.index0) }}">
				<td>{{ entity.id }}</td>
				<td>
					{% if entity.coverPath %}
						<img src="{{ asset(entity.coverWebUrl) | imagine_filter('88x31')}}" />
					{% endif %}
				</td>
				<td><a href="{{ path('gospel_partner_show', {id: entity.id}) }}">{{ entity.title }}</a></td>
				<td>{{ entity.category }}</td>
				<td>{% if entity.status == 1 %}是{% else %}否{% endif %}</td>
				<td>{{ entity.publishedAt|date('Y-m-d H:m:s') }}</td>
				<td>
								<form onsubmit="return confirm('确定要删除: {{ entity.title }}？');" style="display: inline;" method="post" action="{{ path('gospel_partner_delete', {id: entity.id}) }}">
					<div class="btn-group">
						<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
							操作
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu">
							<li class="edit odd first dropbutton-action"><a href="{{ path('gospel_partner_show', {id: entity.id}) }}">查看</a></li>
							<li class="edit odd first dropbutton-action"><a href="{{ path('gospel_partner_update', {id: entity.id}) }}">编辑</a></li>
							<li class="edit odd first dropbutton-action">
        						<a class="submit-closest-form" href="#">删除</a>
								</li>
						</ul>
					</div>
    <input type="hidden" value="DELETE" name="_method">
</form>
				</td>
			</tr>
	{% endfor %}
	{% endif %}
		</tbody>
	</table>
{% if partners.haveToPaginate()|default(false) %}
{{ pagerfanta(partners, 'twitter_bootstrap_translated', options|default({})) }}
{% endif %}
{% endblock %}

src/Gospel/Bundle/CoreBundle/Resources/views/Partner/load.html.twig
{% extends '::backend.html.twig' %}
{% block body -%}
Loading action...
{{ msg|raw }}
{% endblock %}

src/Gospel/Bundle/CoreBundle/Resources/views/Partner/show.html.twig
{% extends '::backend.html.twig' %}
{% from 'GospelCoreBundle:Macros:misc.html.twig' import editNbackBtn %}
{% block body -%}
    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ partner.id }}</td>
            </tr>
            <tr>
                <th>标题</th>
                <td>{{ partner.title }}</td>
            </tr>
            <tr>
                <th>上次修改时间</th>
                <td>{{ partner.updatedAt|date('Y-m-d H:m:s') }}</td>
            </tr>
            <tr>
                <th>创建时间</th>
                <td>{{ partner.createAt|date('Y-m-d H:m:s') }}</td>
            </tr>
        </tbody>
    </table>

{{ editNbackBtn('gospel_partner_update', 'gospel_partner_index', partner) }}
{% endblock %}

src/Gospel/Bundle/CoreBundle/Resources/views/Partner/update.html.twig
{% extends 'GospelCoreBundle:Partner:form.layout.html.twig' %}
{% block header %}
<h1 class="page-title">修改合作伙伴 —— {{ partner.title }}</h1>
{% endblock %}